apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-addon-manager
subjects:
  - kind: ServiceAccount
    name: logging-addon-manager-sa
    namespace: open-cluster-management
