apiVersion: v1
kind: Secret
metadata:
  name: mtls-spoke-hub
  namespace: openshift-logging
  labels:
    app: {{ template "lokihelm.name" . }}
    chart: {{ template "lokihelm.chart" . }}
    release: {{ .Release.Name }}
data:
  'tls.crt': {{ .Values.mTLS.cert | b64enc }}
  'tls.key': {{ .Values.mTLS.key | b64enc }}
  'ca-bundle.crt': {{ .Values.mTLS.caBundle | b64enc }}