kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:logging-addon:klusterlet-work:agent
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["operatorgroups"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]