namespace: open-cluster-management-hub

resources:
  - resources/cluster_role_binding.yaml
  - resources/cluster_role.yaml
  - resources/manager_deployment.yaml
  - resources/service_account.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
