{{- define "addOnDeploymentConfig" }}
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: logging-omc-addon
  namespace: {{ .Values.name }}
  labels:
    app: {{ template "addOnClusterResources.name" . }}
    chart: {{ template "addOnClusterResources.chart" . }}
    release: {{ .Release.Name }}
spec:
  customizedVariables:
    - name: lokiURL
      value: {{ .Values.lokiURL }}/api/logs/v1/{{ .Values.name }}
{{- end }}