{{- define "certificate" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    app: {{ template "addOnClusterResources.name" . }}
    chart: {{ template "addOnClusterResources.chart" . }}
    release: {{ .Release.Name }}
spec:
  secretName: {{ .Values.name }}
  commonName: {{ .Values.name }} 
  subject:
    organizationalUnits:
      - logging-omc-addon
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  dnsNames:
    - collector.openshift-logging.svc
  usages:
    - client auth
    - key encipherment
    - digital signature
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
{{- end }}