{{- define "certificate" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    app: {{ template "addOnClusterResources.name" . }}
    chart: {{ template "addOnClusterResources.chart" . }}
    release: {{ .Release.Name }}
spec:
  secretName: {{ .Values.name }}
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  dnsNames:
    - devcluster.openshift.com
  usages:
    - server auth
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
{{- end }}