apiVersion: v1
kind: Secret
metadata:
  name: hub-lokistack-s3-credentials
  namespace: openshift-logging
type: Opaque
data:
  endpoint: {{ .Values.lokiS3Bucket.endpoint | b64enc }}
  region: {{ .Values.lokiS3Bucket.region | b64enc }}
  access_key_id: {{ .Values.lokiS3Bucket.accessKeyID | b64enc }}
  access_key_secret: {{ .Values.lokiS3Bucket.accessKeySecret | b64enc }}
  bucketnames: {{ .Values.lokiS3Bucket.bucketnames | b64enc }}