apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-hub-logging
spec:
  disabled: false
  policy-templates:
  - extraDependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: ConfigurationPolicy
      name: redhat-loki-operator
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: redhat-openshift-logging
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
        # Install cert-manager to provide TLS secrets
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager-operator        
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              annotations:
                olm.providedAPIs: CertManager.v1alpha1.operator.openshift.io,Certificate.v1.cert-manager.io,CertificateRequest.v1.cert-manager.io,Challenge.v1.acme.cert-manager.io,ClusterIssuer.v1.cert-manager.io,Issuer.v1.cert-manager.io,Order.v1.acme.cert-manager.io
              name: cert-manager-operator
              namespace: cert-manager-operator
            spec:
              targetNamespaces:
              - cert-manager-operator
              upgradeStrategy: Default
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/openshift-cert-manager-operator.cert-manager-operator: ""
              name: openshift-cert-manager-operator
              namespace: cert-manager-operator
            spec:
              channel: stable-v1
              installPlanApproval: Automatic
              name: openshift-cert-manager-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
        # End of cert-manager installation
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: redhat-loki-operator
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              annotations:
                olm.providedAPIs: AlertingRule.v1.loki.grafana.com,LokiStack.v1.loki.grafana.com,RecordingRule.v1.loki.grafana.com,RulerConfig.v1.loki.grafana.com
              name: openshift-operators-redhat
              namespace: openshift-operators-redhat
            spec:
              upgradeStrategy: Default
        # Commented out until 5.8 is released which contains mTLS support
        # - complianceType: musthave
        #   objectDefinition:
        #     apiVersion: operators.coreos.com/v1alpha1
        #     kind: Subscription
        #     metadata:
        #       labels:
        #         operators.coreos.com/loki-operator.openshift-operators-redhat: ''
        #       name: loki-operator
        #       namespace: openshift-operators-redhat
        #     spec:
        #       channel: stable
        #       installPlanApproval: Automatic
        #       name: loki-operator
        #       source: redhat-operators
        #       sourceNamespace: openshift-marketplace
  - extraDependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: ConfigurationPolicy
      name: redhat-loki-operator
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: lokistack-hub
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: loki.grafana.com/v1
            kind: LokiStack
            metadata:
              name: lokistack-hub
              namespace: openshift-logging
            spec:
              size: 1x.extra-small
              storage:
                secret:
                  name: hub-lokistack-s3-credentials
                  type: s3
              storageClassName: gp3-csi
              tenants:
                authentication:
{{- range $_, $cluster_conf := .Values.clusters }}
                - mTLS:
                    ca:
                      caName: {{ $cluster_conf.name }}
                  tenantId: {{ $cluster_conf.name }}
                  tenantName: {{ $cluster_conf.name }}
{{- end }}
                authorization:
                  roleBindings:
                  - name: write-logs
                    roles:
                    - write-logs
                    subjects:
                    - kind: group
                      name: logging-omc-addon
                  - name: read-logs
                    roles:
                    - read-logs
                    subjects:
                    - kind: group
                      name: logging-omc-addon
                  roles:
                  - name: read-logs
                    permissions:
                    - read
                    resources:
                    - logs
                    tenants:
{{- range $_, $cluster_conf := .Values.clusters }}
                    - {{ $cluster_conf.name }}
{{- end }}
                  - name: write-logs
                    permissions:
                    - write
                    resources:
                    - logs
                    tenants:
{{- range $_, $cluster_conf := .Values.clusters }}
                    - {{ $cluster_conf.name }}
{{- end }}
                mode: static
