# By default the SA used by OCM to apply ManifestWorks does not have the 
# necessary premissions to create OperatorGroups', since we install the logging
# operator using the AdddOn we need to grant this SA these premissions
# https://open-cluster-management.io/concepts/manifestwork/#permission-setting-for-work-agent
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:logging-addon:klusterlet-work:agent
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["operatorgroups"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]